[package]
name = "jupiter"
version = "0.1.0"
edition = "2021"


[dependencies]
repository = { workspace = true }
log = "0.4.21"
serde = { version = "1.0.202", features = ["derive"] }
anyhow = "1.0.83"
serde_yaml = "0.9.34+deprecated"
